dependencies:
  - nbserverproxy
  - conda-forge::param=1.9.0
  - conda-forge::pyviz_comms=0.7.2
  - conda-forge::datashader
  - conda-forge::bokeh
  - conda-forge::panel=0.5.1
  - tornado<6  
  - conda-forge::scrapy
